version: '3'

services:
  sql_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      ROOT_PASSWORD: 1234
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: training
      POSTGRES_DB: training
